name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH para conectar con las EC2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.239.0.46 >> ~/.ssh/known_hosts
          ssh-keyscan -H 44.201.131.252 >> ~/.ssh/known_hosts
          
      # Paso 3: Desplegar los archivos en la primera instancia EC2
      - name: Deploy to Instance 1
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@34.239.0.46 << 'EOF'
            cd /home/ec2-user/Ec2HtmlYml || git clone https://github.com/meybili19/Ec2HtmlYml.git
            cd Ec2HtmlYml
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo cp instance-ip.php /var/www/html/
            sudo systemctl restart nginx
          EOF

      # Paso 4: Desplegar los archivos en la segunda instancia EC2
      - name: Deploy to Instance 2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@44.201.131.252 << 'EOF'
            cd /home/ec2-user/Ec2HtmlYml || git clone https://github.com/meybili19/Ec2HtmlYml.git
            cd Ec2HtmlYml
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo cp instance-ip.php /var/www/html/
            sudo systemctl restart nginx
          EOF
