name: Deploy to EC2

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed

jobs:
  deploy_to_qa:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 44.210.128.144 >> ~/.ssh/known_hosts
          ssh-keyscan -H 3.88.111.215 >> ~/.ssh/known_hosts
          ssh-keyscan -H 54.87.132.189 >> ~/.ssh/known_hosts
          ssh-keyscan -H 54.167.140.200 >> ~/.ssh/known_hosts

      - name: Deploy to QA Instance
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.167.140.200 << 'EOF'
            cd /home/ec2-user/Ec2HtmlYml || git clone https://github.com/meybili19/Ec2HtmlYml.git
            cd Ec2HtmlYml
            git pull origin test
            sudo cp index.html /var/www/html/
            sudo cp instance-ip.php /var/www/html/
            sudo systemctl restart nginx
          EOF

  deploy_to_production:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 44.210.128.144 >> ~/.ssh/known_hosts
          ssh-keyscan -H 3.88.111.215 >> ~/.ssh/known_hosts
          ssh-keyscan -H 54.87.132.189 >> ~/.ssh/known_hosts
          ssh-keyscan -H 54.167.140.200 >> ~/.ssh/known_hosts

      - name: Deploy to Instance 1
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@44.210.128.144 << 'EOF'
            cd /home/ec2-user/Ec2HtmlYml || git clone https://github.com/meybili19/Ec2HtmlYml.git
            cd Ec2HtmlYml
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo cp instance-ip.php /var/www/html/
            sudo systemctl restart nginx
          EOF

      - name: Deploy to Instance 2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.88.111.215 << 'EOF'
            cd /home/ec2-user/Ec2HtmlYml || git clone https://github.com/meybili19/Ec2HtmlYml.git
            cd Ec2HtmlYml
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo cp instance-ip.php /var/www/html/
            sudo systemctl restart nginx
          EOF

      - name: Deploy to Instance 3
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.87.132.189 << 'EOF'
            cd /home/ec2-user/Ec2HtmlYml || git clone https://github.com/meybili19/Ec2HtmlYml.git
            cd Ec2HtmlYml
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo cp instance-ip.php /var/www/html/
            sudo systemctl restart nginx
          EOF
