name: Deploy to EC2

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main

jobs:
  deploy_to_qa:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH para conectar con las EC2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 52.55.91.91 >> ~/.ssh/known_hosts
          ssh-keyscan -H 52.90.89.186 >> ~/.ssh/known_hosts
          ssh-keyscan -H 44.202.47.119 >> ~/.ssh/known_hosts
          ssh-keyscan -H 3.83.17.47 >> ~/.ssh/known_hosts
      # Paso 3: Desplegar los archivos en la primera instancia EC2
      - name: Deploy to Instance 1
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@52.55.91.91 << 'EOF'
            cd /home/ec2-user/Html-Balance || git clone https://github.com/meybili19/Ec2HtmlYml.git
            cd Html-Balance
            git pull origin main  # Actualizar los archivos del repositorio
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF

      # Paso 4: Desplegar los archivos en la segunda instancia EC2
      - name: Deploy to Instance 2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@52.90.89.186 << 'EOF'
            cd /home/ec2-user/Html-Balance || git clone https://github.com/meybili19/Ec2HtmlYml.git
            cd Html-Balance
            git pull origin main  # Actualizar los archivos del repositorio
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF

          # Paso 4: Desplegar los archivos en la segunda instancia EC2
      - name: Deploy to Instance 3
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@44.202.47.119 << 'EOF'
            cd /home/ec2-user/Html-Balance || git clone https://github.com/meybili19/Ec2HtmlYml.git
            cd Html-Balance
            git pull origin main  # Actualizar los archivos del repositorio
            sudo cp index.html /var/www/html/  # Copiar index.html al directorio de Nginx
            sudo systemctl restart nginx  # Reiniciar Nginx
          EOF
